apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: tekton-rbac-test-admins
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2R6Q0NBVjhDQVFBd01qRU9NQXdHQTFVRUF3d0ZZV1J0YVc0eElEQWVCZ05WQkFvTUYzUmxhM1J2YmkxeQpZbUZqTFhSbGMzUXRZV1J0YVc1ek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjBnNFRhaEtGYUZUUVJHR1ZSVnRLWVpHS2l1WTE2MHlMZFliZUppS0FlTDFQNGpDRzNuTVVGVTYyOFFDOWJwb3YKYVZTRkEvSTMrK3F4RWVlVUt3QTNzTTlmbU1yTjBWYm9TU3Yra3I3bEErRi9BYW5HVUpJOThRYjQzNWJEZUxodwpBNldveGRFb0pMTkR4R2FZRDZ3OGE5bHhoQlhRT1hBWE9taW1tSWJ6NmxCbEl2S0RCUzNBWTBHS1JZcmJsUWtLCkJoVTVQZWFHdFlYdlBUaGhVTWVzbHkzd3p3cVM5Z0dtYkxvdmZNbndEQ3dXT2NyL1NHaWczcUMvY29oV08xdTgKaVhZUk9ScXM2WnV3bzNkSkZ3cEUyeW14REh3SHNFT2pTdVlDRVZUMlJvMFdJd1RaNVRoaXNJbHNlcXRuQ0poaQpEN3FKeEJRTys5OElsZWFjNzhISWRRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDY3cvajljCkd1R2JqZ0dQSGZuRlc4RXNHZ0J0NjFoTzJkZFpXSVZrRkJXMjZpOVh2UURtcXNROUdpLzhhR2NnM1o0TjBtdWMKcFRsU3VYSTI0M3ljYnl0NDl6a1lyckZZNk1IUHJQSDE2NFFIVytLNVZoSzVRWm5NWkdDajYyclk3dzI0K09nagpNMTY1bTBudmxOcDN1YkZwbEp4S2pHcHh1SlBmQWp1TXVWTHppeFdIZXpEdXVVMmdhbnl6M0ZRTXNpWEhvNVJuCnFGNjNmdkFQZ0J4bEpIaytoajNOb09INWEzd0hyUE5jeFZDVUVjN2t2eElldk1FazVPOGxnYm9MZC9xTUR6UkIKZnQrSVVJTVY0aG1ERGJ0VnBuRVBTbkNncHJQM1RmNXo4cm1Xdk9oM0NGbnZoQlY2M2t3R01WTjFtVmNhVUZ4cApxRXlDT0lRTmVrS3pYeE09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth