apiVersion: v1
kind: Namespace
metadata:
  name: admins-namespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: admins-namespace
  name: admins-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - get
  - update
  - patch
  - delete
  - list
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: developers-namespace
  name: admins-role-for-development
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - get
  - update
  - patch
  - delete
  - list
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admins-rolebinding
  namespace: admins-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admins-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tekton-rbac-test-admins
