apiVersion: v1
kind: Namespace
metadata:
  name: developers-namespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers-role
  namespace: developers-namespace
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: developers-namespace
  name: developers-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tekton-rbac-test-developers

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admins-role-for-development
  namespace: developers-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admins-role-for-development
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tekton-rbac-test-admins
