apiVersion: v1
kind: Namespace
metadata:
  name: rbac-only-namespace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-only-role
  namespace: rbac-only-namespace
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rbac-only-namespace
  name: rbac-only-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-only-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tekton-rbac-test-rbac-only
